# YOUR NAME OR TITLE OF YOUR SITE
name: Matthew Kutarna

# YOUR BRAND/PERSONAL TAGLINE
tagline: Howdy, I'm Matthew Kutarna. I'm an aspiring Data Scientist / Machine Learning Engineer Lover from in Vancouver area. 

# YOUR/BRAND IMAGE URL
Image_URL: https://mkutarna.github.io/img/profile.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://images.unsplash.com/photo-1550439062-609e1531270e

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # LINKEDIN
  - Name: LinkedIn
    URL: https://www.linkedin.com/in
    Username: matthewkutarna
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: mkutarna
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 'mailto:matthewkutarna@gmail.com'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # CUSTOM LINK
  - Name: HuggingFace Space
    URL: https://huggingface.co/spaces/mkutarna/audiobook_gen
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
